name: Discord Commit Notify

on:
  push:
  pull_request:

jobs:
  notify:
    name: commit_msg
    runs-on: ubuntu-latest
    steps:
    
    - name: check_out
      uses: actions/checkout@v2.4.0
      with:
          ref: ${{ github.head_ref }}
          
    - name: get_commit_msg
      run: |
        echo "Commit_Message=$(git log --pretty=oneline --all --abbrev-commit)" >> $GITHUB_ENV
    - name: notify
      uses: appleboy/discord-action@0.0.3
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        args: "${{ github.event_name }} by @${{ github.actor }} \nmessage: ${{ env.Commit_Message }}"
